# Dataset splitting

In [2]:
#import libraries
import pandas as pd
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split

In [19]:
#Read the dataset
df = pd.read_csv("Real-estate.csv")
df.head()

,No,X1 transaction date,X2 house age,X3 distance to the nearest MRT station,X4 number of convenience stores,X5 latitude,X6 longitude,Y house price of unit area
0,1,2012.917,32.0,84.87882,10,24.98298,121.54024,37.9
1,2,2012.917,19.5,306.59470,9,24.98034,121.53951,42.2
2,3,2013.583,13.3,561.98450,5,24.98746,121.54391,47.3
3,4,2013.500,13.3,561.98450,5,24.98746,121.54391,54.8
4,5,2012.833,5.0,390.56840,5,24.97937,121.54245,43.1

In [20]:
#get the location
X= df.iloc[:, :-1]
Y= df.iloc[:, -1]

In [21]:
# split the dataset
X_train, X_test, Y_train, Y_test =train_test_split(X, Y, test_size=0.2, random_state=0)

In [22]:
X_train

,No,X1 transaction date,X2 house age,X3 distance to the nearest MRT station,X4 number of convenience stores,X5 latitude,X6 longitude
302,303,2013.500,16.5,2288.01100,3,24.95885,121.51359
20,21,2013.417,4.5,2275.87700,3,24.96314,121.51151
303,304,2013.500,38.3,439.71050,0,24.97161,121.53423
142,143,2013.417,19.8,640.60710,5,24.97017,121.54647
14,15,2013.500,13.2,1164.83800,4,24.99156,121.53406
...,...,...,...,...,...,...,...
323,324,2013.417,28.6,197.13380,6,24.97631,121.54436
192,193,2013.167,43.8,57.58945,7,24.96750,121.54069
117,118,2013.000,13.6,4197.34900,0,24.93885,121.50383
47,48,2013.583,35.9,640.73910,3,24.97563,121.53715
172,173,2013.583,6.6,90.45606,9,24.97433,121.54310

In [23]:
X_test

,No,X1 transaction date,X2 house age,X3 distance to the nearest MRT station,X4 number of convenience stores,X5 latitude,X6 longitude
356,357,2012.833,10.3,211.4473,1,24.97417,121.52999
170,171,2013.333,24.0,4527.6870,0,24.94741,121.49628
224,225,2013.333,34.5,324.9419,6,24.97814,121.54170
331,332,2013.333,25.6,4519.6900,0,24.94826,121.49587
306,307,2013.500,14.4,169.9803,1,24.97369,121.52979
...,...,...,...,...,...,...,...
308,309,2013.417,16.4,289.3248,5,24.98203,121.54348
100,101,2013.500,17.5,964.7496,4,24.98872,121.53411
7,8,2013.417,20.3,287.6025,6,24.98042,121.54228
22,23,2012.917,14.7,1360.1390,1,24.95204,121.54842
68,69,2013.417,30.4,464.2230,6,24.97964,121.53805

In [24]:
Y_train

302    23.2
20     29.3
303    38.4
142    37.5
14     34.3
       ...
323    42.5
192    42.7
117    13.0
47     61.5
172    58.1
Name: Y house price of unit area, Length: 331, dtype: float64

In [25]:
Y_test

356    45.3
170    14.4
224    46.0
331    15.6
306    50.2
       ...
308    53.0
100    38.2
7      46.7
22     24.6
68     36.2
Name: Y house price of unit area, Length: 83, dtype: float64